/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ConsultasDAO;
import VO.libroVO;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author undercoder
 */
public class GestionLibro extends javax.swing.JDialog {

    ConsultasDAO consultaDAO = new ConsultasDAO();
    public static DefaultTableModel modelolibros;

    /**
     * Creates new form GestionLibro
     */
    public GestionLibro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String pilas[][] = {};
        String columnas[] = {"Id_libro", "Titulo", "Editorial", "Autor"};
        jTable1.setOpaque(false);
        ((DefaultTableCellRenderer) jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jTable1.setShowGrid(false);
        modelolibros = new DefaultTableModel(pilas, columnas);
        jTable1.setModel(modelolibros);
       imprimir();
    }

    public void imprimir() {
        LinkedList datos = new LinkedList();
        datos = consultaDAO.imprimir();
        if (!datos.isEmpty()) {
            for (int i = 0; i < datos.size(); i++) {
                libroVO loslibros = (libroVO) datos.get(i);
                for (int y = modelolibros.getRowCount() - 1; y >= 0; y--) {
                    modelolibros.removeRow(y);
                }
                for (int h = 0; h < datos.size(); h++) {
                    libroVO p1 = (libroVO) datos.get(h);
                    modelolibros.insertRow(h, new Object[]{});
                    modelolibros.setValueAt(p1.getid(), h, 0);
                    modelolibros.setValueAt(p1.gettitulo(), h, 1);
                    modelolibros.setValueAt(p1.geteditorial(), h, 2);
                    modelolibros.setValueAt(p1.getarea(), h, 3);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        idlibro = new javax.swing.JTextField();
        titulolibro = new javax.swing.JTextField();
        editorialibro = new javax.swing.JTextField();
        arealibro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar y Eliminar Libros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/seo_web-16-32.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 153, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/close-circle-red-32.png"))); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 153, -1, -1));
        getContentPane().add(idlibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 37, 113, -1));
        getContentPane().add(titulolibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 63, 113, -1));

        editorialibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorialibroActionPerformed(evt);
            }
        });
        getContentPane().add(editorialibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 89, 113, -1));
        getContentPane().add(arealibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 115, 113, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("titulo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 66, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("editorial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 92, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("area");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 118, -1, -1));

        jTable1.setFont(new java.awt.Font("Ravie", 3, 10)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id_libro", "Titulo", "Editorial", "Area"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 234, -1, 98));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/biblioteca-cultura.jpg"))); // NOI18N
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (idlibro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta Id");
            idlibro.requestFocus();
        } else if (titulolibro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el titulo");
            titulolibro.requestFocus();
        } else if (editorialibro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta la editorial");
            editorialibro.requestFocus();
        } else if (arealibro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el area");
            arealibro.requestFocus();
        } else {
            int id = Integer.parseInt(idlibro.getText());
            consultaDAO.registrarlibro(id, titulolibro.getText(), editorialibro.getText(), arealibro.getText());
            imprimir();
            JOptionPane.showMessageDialog(rootPane, "El Libro ha sido Guardado");
            idlibro.setText("");
            titulolibro.setText("");
            editorialibro.setText("");
            arealibro.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editorialibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorialibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorialibroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String xd = JOptionPane.showInputDialog("Introduce el numero que deseas eliminar?");

        if (xd != null) {
            int a = Integer.parseInt(xd);

            consultaDAO.eliminarLibro(a);
            imprimir();

            JOptionPane.showMessageDialog(rootPane, "El Libro ha sido eliminado");

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionLibro dialog = new GestionLibro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arealibro;
    private javax.swing.JTextField editorialibro;
    private javax.swing.JTextField idlibro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField titulolibro;
    // End of variables declaration//GEN-END:variables
}
