/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ConsultasDAO;
import VO.Reporte4VO;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author undercoder
 */
public class Reporte4 extends javax.swing.JDialog {

    ConsultasDAO consultaDAO = new ConsultasDAO();
    public static DefaultTableModel modeloreporte4;

    /**
     * Creates new form Reporte4
     */
    public Reporte4(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String pilas[][] = {};
        String columnas[] = {"Autor", "Id", "Nombre Del Libro", "Editorial", "Area"};
        jTable1.setOpaque(false);
        ((DefaultTableCellRenderer) jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jTable1.setShowGrid(false);
        modeloreporte4 = new DefaultTableModel(pilas, columnas);
        jTable1.setModel(modeloreporte4);
    }

    public void imprimir() {
        LinkedList datos = new LinkedList();
        datos = consultaDAO.imprimir2();
        if (!datos.isEmpty()) {
            for (int i = 0; i < datos.size(); i++) {
                Reporte4VO loslibros = (Reporte4VO) datos.get(i);
                for (int y = modeloreporte4.getRowCount() - 1; y >= 0; y--) {
                    modeloreporte4.removeRow(y);
                }
                for (int h = 0; h < datos.size(); h++) {
                    Reporte4VO p1 = (Reporte4VO) datos.get(h);
                    modeloreporte4.insertRow(h, new Object[]{});
                    modeloreporte4.setValueAt(p1.getAutor(), h, 0);
                    modeloreporte4.setValueAt(p1.getId(), h, 1);
                    modeloreporte4.setValueAt(p1.getTitulo(), h, 2);
                    modeloreporte4.setValueAt(p1.getEditorial(), h, 3);
                    modeloreporte4.setValueAt(p1.getArea(), h, 4);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autor-Libros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/list-32.png"))); // NOI18N
        jButton1.setText("Listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 70, 550, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono-biblioteca-300x300.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 310, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = "";
        nombre = JOptionPane.showInputDialog("Ingrese el nombre del autor a buscar");
        if (nombre != null) {
            LinkedList datos = new LinkedList();
            datos = consultaDAO.consulta4(nombre);
            if (!datos.isEmpty()) {
                for (int i = 0; i < datos.size(); i++) {
                    Reporte4VO elreporte = (Reporte4VO) datos.get(i);
                    for (int y = modeloreporte4.getRowCount() - 1; y >= 0; y--) {
                        modeloreporte4.removeRow(y);
                    }
                    for (int h = 0; h < datos.size(); h++) {
                        Reporte4VO p1 = (Reporte4VO) datos.get(h);
                        modeloreporte4.insertRow(h, new Object[]{});
                        modeloreporte4.setValueAt(p1.getAutor(), h, 0);
                        modeloreporte4.setValueAt(p1.getId(), h, 1);
                        modeloreporte4.setValueAt(p1.getTitulo(), h, 2);
                        modeloreporte4.setValueAt(p1.getArea(), h, 4);
                        modeloreporte4.setValueAt(p1.getEditorial(), h, 3);
                    }
                }
            } else if (datos.isEmpty()) {
                imprimir();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Haz cancelado la operacion :V");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reporte4 dialog = new Reporte4(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
